library(dplyr)
library(data.table)
install.packages("png")
library(png)
power <- read.csv("./household_power_consumption.txt", sep=";", na.strings="?",stringsAsFactors = FALSE, colClasses = c("character", "character","numeric","numeric","numeric","numeric","numeric","numeric","numeric"))
power$Date <- as.Date (power$Date, format = "%d/%m/%Y")
power$Time <- strptime(paste(power$Date, power$Time), "%F %T")
powersubset <- subset(power, power$Date == "2007-02-01"| power$Date == "2007-02-02")
plot(powersubset$Time, powersubset$Sub_metering_1, type = "l", xlab = "", ylab = "Energy Submetering")
lines(powersubset$Time, powersubset$Sub_metering_2, col = "red")
lines(powersubset$Time, powersubset$Sub_metering_3, col = "blue")
legend("topright", lty = 1, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.copy (png, file = "plot3.png", width=480, height=480)
dev.off()
