plot(powersubset$Time, powersubset$Sub_metering_1, type = "l", xlab = "", ylab = "Energy Submetering")
lines(powersubset$Time, powersubset$Sub_metering_2, col = "red")
lines(powersubset$Time, powersubset$Sub_metering_3, col = "blue")
legend("topright", lty = 1, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.copy (png, file = "plot3.png", width=480, height=480)
dev.off()
