library(dplyr)
library(data.table)
install.packages("png")
library(png)
power <- read.csv("./household_power_consumption.txt", sep=";", na.strings="?",stringsAsFactors = FALSE, colClasses = c("character", "character","numeric","numeric","numeric","numeric","numeric","numeric","numeric"))
power$Date <- as.Date (power$Date, format = "%d/%m/%Y")
power$Time <- strptime(paste(power$Date, power$Time), "%F %T")
powersubset <- subset(power, power$Date == "2007-02-01"| power$Date == "2007-02-02")
par (mfrow = c(2,2), mar = c(2,4,2,2))
plot(powersubset$Time, powersubset$Global_active_power, type = "l", xlab = "", ylab = "Global Active Power")
plot(powersubset$Time, powersubset$Voltage, type = "l", xlab = "datetime", ylab = "Voltage")
plot(powersubset$Time, powersubset$Sub_metering_1, type = "l", xlab = "", ylab = "Energy Submetering")
lines(powersubset$Time, powersubset$Sub_metering_2, col = "red")
lines(powersubset$Time, powersubset$Sub_metering_3, col = "blue")
legend("topright", lty = 1, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
plot(powersubset$Time, powersubset$Global_reactive_power, type = "l", xlab = "datetime", ylab = "Global_reactive_power")
dev.copy (png, file = "plot4.png", width=480, height=480)
dev.off()
